import { createHash } from 'node:crypto';
import { readFileSync, writeFileSync } from 'node:fs';
import { pathToFileURL } from 'node:url';

// Only pure validators, native sheet reads, formatting and owner authorization.
// Repair validators remain necessary to read existing immutable repair events.
export const READER_FUNCTIONS = Object.freeze([
  'authenticatedPromotionOwner_', 'canonicalPromotionJson_', 'canonicalPromotionRepairJson_', 'exactPromotionFields_', 'failPromotion_',
  'plainPromotionObject_', 'promotionCellText_', 'promotionId_', 'promotionRank_', 'promotionRepairCellPosition_', 'promotionRepairDate_',
  'promotionRepairDigest_', 'promotionRepairFieldSnapshot_', 'promotionRepairFingerprint_', 'promotionRepairSourceRanges_', 'promotionSuccess_',
  'promotionText_', 'promotionToday_', 'rankSnapshot_', 'readPromotionHistory_', 'requirePromotionSheet_', 'requirePromotionStudent_',
  'storedPromotionBoolean_', 'storedPromotionRank_', 'validLegacyPromotionBaseline_', 'validatePromotionRepairEvidenceBinding_',
  'validatePromotionRepairRankConflict_', 'validatePromotionRepairTransition_', 'validatePromotionRepair_'
]);
const CONSTANTS = ['PROMOTION_TEST_TITLE_', 'PROMOTION_TIME_ZONE_', 'PROMOTION_BELTS_', 'PROMOTION_APPROVERS_', 'STUDENT_HEADERS_', 'PROMOTION_HISTORY_HEADERS_'];

export function buildReader(source) {
  source = source.replace(/\r\n/g, '\n');
  const declarations = [...source.matchAll(/^(?:function|const) ([A-Za-z0-9_]+)/gm)];
  const chunks = new Map(declarations.map((match, index) => [match[1], source.slice(match.index, declarations[index + 1]?.index ?? source.length).trimEnd()]));
  const selected = [...CONSTANTS, ...READER_FUNCTIONS];
  for (const name of selected) if (!chunks.has(name)) throw new Error('Missing read-only dependency: ' + name);
  const body = selected.map(name => chunks.get(name)).join('\n\n');
  for (const match of body.matchAll(/\b([A-Za-z0-9_]+_)\s*\(/g)) {
    if (chunks.has(match[1]) && !selected.includes(match[1])) throw new Error('Unselected dependency: ' + match[1]);
  }
  if (/\b(?:appendRow|setValues|setValue|clearContent|deleteRow|insertSheet|flush|openByUrl)\s*\(/.test(body)) throw new Error('Unexpected mutation in reader closure');
  return '// Generated by promotions/api-readonly/build.mjs; do not edit.\n'
    + '// Shared Code.gs SHA256 (normalized LF): ' + createHash('sha256').update(source).digest('hex') + '\n\n' + body + '\n';
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  const generated = buildReader(readFileSync(new URL('../Code.gs', import.meta.url), 'utf8'));
  const destination = new URL('./Reader.gs', import.meta.url);
  if (process.argv.includes('--check')) {
    if (readFileSync(destination, 'utf8').replace(/\r\n/g, '\n') !== generated) throw new Error('Generated Reader.gs is stale');
    console.log('Read-only reader matches the exact shared validator closure.');
  } else {
    writeFileSync(destination, generated);
    console.log('Generated read-only Reader.gs.');
  }
}
